[build]
  # This will be run the site build
  command = "npm run build"
  # This is the directory is publishing to netlify's CDN
  publish = "dist/pic-connected-bee"
  # functions build directory
  functions = "functions"
